name: Confirm Flaky Test (inputs)

on:
  workflow_dispatch:
    inputs:
      repo_url:   { description: 'Git repo URL', required: true, type: string }
      sha:        { description: 'Commit SHA (optional)', required: false, type: string, default: '' }
      module:     { description: 'Maven module path (use "." for root)', required: true, type: string }
      fqtn:       { description: 'pkg.Class.method', required: true, type: string }
      nondexRuns: { description: 'NonDex runs', required: true, type: string, default: '200' }
      java:       { description: 'Java version (8/11/17)', required: true, type: string, default: '11' }

jobs:
  confirm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java }}

      - name: Clone
        run: |
          git clone "${{ inputs.repo_url }}" proj
          cd proj
          if [ -n "${{ inputs.sha }}" ]; then git checkout "${{ inputs.sha }}"; fi
          git rev-parse HEAD

      - name: Build (skip tests)
        working-directory: proj
        run: |
          set -o pipefail
          MOD="${{ inputs.module }}"
          mvn -q -DskipTests -Dgpg.skip=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -pl "$MOD" -am clean install || \
          mvn -q -DskipTests -Dgpg.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true -Dlicense.skip=true -Dcheckstyle.skip -pl "$MOD" -am clean install


      - name: Run test (normal)
        id: unit
        working-directory: proj
        run: |
          set -o pipefail
          FQTN="${{ inputs.fqtn }}"
          CLASS="${FQTN%.*}"
          METHOD="${FQTN##*.}"
          mvn -q -pl "${{ inputs.module }}" test -Dtest="${CLASS}#${METHOD}" 2>&1 | tee ../ci-build.log

      - name: Run with NonDex
        id: nondex
        if: ${{ steps.unit.outcome == 'success' }}
        working-directory: proj
        continue-on-error: true
        run: |
          set -o pipefail
          FQTN="${{ inputs.fqtn }}"
          CLASS="${FQTN%.*}"
          METHOD="${FQTN##*.}"
          mvn -q -pl "${{ inputs.module }}" edu.illinois:nondex-maven-plugin:2.1.1:nondex \
             -Dtest="${CLASS}#${METHOD}" -DnondexRuns="${{ inputs.nondexRuns }}" 2>&1 | tee -a ../ci-build.log

      - name: Upload ci-build.log
        uses: actions/upload-artifact@v4
        with:
          name: ci-build.log
          path: ci-build.log

      - name: Decide
        if: ${{ always() }}
        run: |
          echo "unit:   ${{ steps.unit.outcome }}"
          echo "nondex: ${{ steps.nondex.outcome }}"
          if [ "${{ steps.unit.outcome }}" = "success" ] && [ "${{ steps.nondex.outcome }}" = "failure" ]; then
            echo "✅ Confirmed flaky."
            exit 0
          else
            echo "❌ Not confirmed."
            exit 1
          fi
