name: Confirm Flaky Test

on:
  workflow_dispatch:

jobs:
  confirm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8   # jBPM at this SHA is happiest on 8; try 11 if needed

      - name: Clone target project
        run: |
          git clone https://github.com/kiegroup/jbpm.git
          cd jbpm
          git checkout f7e80e82b7670c09485ce83869a287ef51dcb59c
          git rev-parse HEAD

      - name: Build deps from repo root (skip tests)
        working-directory: jbpm
        run: |
          set -o pipefail
          mvn -q -DskipTests -pl jbpm-case-mgmt/jbpm-case-mgmt-impl -am clean install || \
          mvn -q -DskipTests -Drat.skip=true -Dlicense.skip=true -Dcheckstyle.skip \
                 -pl jbpm-case-mgmt/jbpm-case-mgmt-impl -am clean install

      - name: Run test normally (expected pass)
        id: unit
        working-directory: jbpm
        run: |
          set -o pipefail
          mvn -q -pl jbpm-case-mgmt/jbpm-case-mgmt-impl test \
             -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testStartEmptyCaseChangeOwner \
             2>&1 | tee ../ci-build.log

      - name: Run test with NonDex (may fail)
        id: nondex
        if: ${{ steps.unit.outcome == 'success' }}
        working-directory: jbpm
        continue-on-error: true
        run: |
          set -o pipefail
          mvn -q -pl jbpm-case-mgmt/jbpm-case-mgmt-impl \
             edu.illinois:nondex-maven-plugin:2.1.1:nondex \
             -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testStartEmptyCaseChangeOwner \
             -DnondexRuns=100 \
             2>&1 | tee -a ../ci-build.log

      - name: Upload ci-build.log
        uses: actions/upload-artifact@v4
        with:
          name: ci-build.log
          path: ci-build.log

      - name: Evaluate outcomes
        if: ${{ always() }}
        run: |
          echo "unit outcome:   ${{ steps.unit.outcome }}"
          echo "nondex outcome: ${{ steps.nondex.outcome }}"
          if [ "${{ steps.unit.outcome }}" = "success" ] && [ "${{ steps.nondex.outcome }}" = "failure" ]; then
            echo "✅ Confirmed flaky."
            exit 0
          else
            echo "❌ Not confirmed. Increase -DnondexRuns or try another test."
            exit 1
          fi
